### ISSUE TITLE
Mounting fails

### ISSUE THREAD

**Issue by ArashJavan** [rauc/rauc#582] opened 2020-04-27 14:08 UTC
Hi, i just follow the example in doc. I build a my linux suing buildroot fpr stm32-dk2 eval board.
Following instructions in this [article](https://bootlin.com/blog/building-a-linux-system-for-the-stm32mp1-remote-firmware-updates/comment-page-1/#comment-2210763). But instead of SWupdate i want to use RAUC :). So after buildroot is finished is just copy the "rootfs.ex4"-File and follow the example article in  RAUC and create an rauc-bundle. On the device i get following error:

```
# rauc install /root/update-2020.04-01.raucb
installing
  0% Installing
  0% Determining slot states
 20% Determining slot states done.
 20% Checking bundle
 20% Verifying signature
 40% Verifying signature done.
 40% Checking bundle done.
100% Installing failed.
LastError: Failed mounting bundle: failed to run mount: Child process exited with code 32
Installing `/root/update-2020.04-01.raucb` failed
```

What am i doing wrong?

Thanks

**Comment by jluebbe** [comment] 2020-04-27 14:19
Did you enable squashfs and loopback block devices in your kernel? Please check the Integration chapter in the docs, especially https://rauc.readthedocs.io/en/latest/integration.html#kernel-configuration.

**Comment by obbardc** [comment] 2020-05-15 14:57
pretty sure this is a duplicate of #562

according to the hassos guys, this patch should fix it: https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/drivers/block/loop.c?id=7e81f99afd91c937f0e66dc135e26c1c4f78b003

can you check this patch is in your kernel or better yet run linux-next ?

**Comment by ejoerns** [comment] 2020-10-24 23:31
@ArashJavan did the patch mentioned resolve your issue, too? Did you have SquashFS support enabled as a module?

**Closed** 2020-10-27 10:38 UTC
Labels: question
