### ISSUE TITLE
How are single child slot updates handled in A/B configuration?

### ISSUE THREAD

**Issue by hongkongkiwi** [rauc/rauc#812] opened 2021-11-17 17:18 UTC
I'm a little bit unclear on an aspect of RAUC when handling subslots on A/B configuration.

```
system a
-> apps a
-> kernel a

system b
-> apps b
-> kernel b
```

In the above configuration, it makes sense to have one RAUC update package which has a complete system (e.g. apps, kernel, system). However, what if you only wanted to update one part slot to save bandwidth for example, I want to update the apps slot.

If I boot into system a, and I want to update only the apps slot, I assume it would just update the apps slot of slot b, in that case will it copy all the other slots so I can reboot into the system b configuration?

**Comment by ejoerns** [comment] 2021-11-17 22:05
> If I boot into system a, and I want to update only the apps slot, I assume it would just update the apps slot of slot b, in that case will it copy all the other slots so I can reboot into the system b configuration?

Currently, it is not implemented this way.

The question would be if we have any benefit of defining this fully symmetric set if our update does not describe the entire system.
If we update `apps` independently from the content of `system`, then we could also write this to a partition decoupled from the A/B scheme. If the motivation is only to have an atomic update of this, probably something like what we have for [bootloaders](https://rauc.readthedocs.io/en/latest/advanced.html#updating-the-bootloader) could be an option.

If we instead still intend to describe the entire system with our update, then the manifest should at least contain the required `system` and `kernel` slot hashes. For this, we had an approach with #376 where copying the content of the active partition could be an interesting extension. The reason I am not fully convinced anymore that this approach was effective is that it probably requires too much pre-knowledge of the slot versions that are out in the field already...

**Comment by Sourabh1107** [comment] 2021-11-18 12:29
We also have similar scenario. More information is provided in [](https://github.com/rauc/rauc/discussions/794#discussioncomment-1645210)

@ejoerns Do you think this as valid use case?

**Comment by hongkongkiwi** [comment] 2021-11-19 06:09
I've been thinking about this, could I force a specific slot to be updated? I couldn't really see that option in rauc install, it seems to automatically select which slot to update.
```
Usage:
  rauc [OPTION*] install <BUNDLE>

Install a bundle

Install options:
  --ignore-compatible           disable compatible check
  --progress                    show progress bar

Application Options:
  -c, --conf=FILENAME           config file
  --cert=PEMFILE|PKCS11-URL     cert file or PKCS#11 URL
  --key=PEMFILE|PKCS11-URL      key file or PKCS#11 URL
  --keyring=PEMFILE             keyring file
  --intermediate=PEMFILE        intermediate CA file name
  --mount=PATH                  mount prefix
  -d, --debug                   enable debug output
  --version                     display version
  -h, --help
```

In my use case, the apps slot is normally independent, so I'm not too worried about consistency. I assume the system is good. If there is a case where this matters and it has to match the current system, then I would issue a full update instead of just an apps only update.

Obviously one solution is to have a completely independent apps slot, but I like the A/B configuration. Another option could be to have apps slot without a parent and then just A/B the apps slot independent of the main system slot. That sounds a bit tricky to keep track of though.

It's a pain, but I could have two different types of update to address this:
- Full system update (includes apps slot) that uses normal RAUC logic
- apps only update which is designed to update the current in use slot only (and I guess a handler script to unmount, flash and remount

**Comment by ejoerns** [comment] 2021-11-19 09:13
> I've been thinking about this, could I force a specific slot to be updated? I couldn't really see that option in rauc install, it seems to automatically select which slot to update.
> 
Not with `rauc install`. There is `rauc write-slot` if you only rely on the image writing capabilities, but this will not help if you want to use verification etc (or would require a full custom handler for example).
> 
> In my use case, the apps slot is normally independent, so I'm not too worried about consistency. I assume the system is good. If there is a case where this matters and it has to match the current system, then I would issue a full update instead of just an apps only update.

The current logic allows defining a non-redundant slot that is not in any child relation with any other slot and updating this.
However, this does not give you atomicity, yet.

Also note that it is not yet conceptually intended to be used this way. This means I can not surely say that this will be supported by future RAUC releases.
However, if we come to the conclusion (in this or further discussions) that this is a valid use case and satisfies most of the 'appfs-only' use cases, it could become a supported use case. But, as noted below, I still see some unresolved issues with that.

> Obviously one solution is to have a completely independent apps slot, but I like the A/B configuration. Another option could be to have apps slot without a parent and then just A/B the apps slot independent of the main system slot. That sounds a bit tricky to keep track of though.

Yes, this is not supported, yet and brings some complexity with it that is currently out of scope for RAUC imho. You would need to have a different appfs slot selection mechanism, similar to how the bootloader selects the right rootfs, etc.

What I see critical about appfs-only updates, and do not probably know all use cases for is

a) How do we update without overwriting the currently running application(s)?
b) How do we handle a failed application update?

If, for atomicity, we think for example about handling appfs updates like we handle bootloader updates for MBR/GPT (having a dedicated partition (single slot) that RAUC can 'move' between a region being twice the size of the partition), this would resolve b) as a broken update does not modify the appfs, but as soon as it was successful it will attempt to modify a currently used partition and thus violate a).

> It's a pain, but I could have two different types of update to address this:
> 
> * Full system update (includes apps slot) that uses normal RAUC logic
> * apps only update which is designed to update the current in use slot only (and I guess a handler script to unmount, flash and remount

What is actually your motivation for not simply updating the rootfs with the appfs together in all cases?
Optimization for (bundle) size or (installation) speed?

**Comment by ejoerns** [comment] 2022-01-26 18:45
Any updates or further suggestions on this? Otherwise I would like to close it :)

**Closed** 2022-06-23 18:41 UTC

**Comment by bhupiister** [comment] 2024-12-06 05:52
Hi, we have a usecase for this.

Rauc supports updating rootfs with A/B. I need a redundant way to update app partition. Can we assign a custom script to such updates? A script that can stop the running apps, enable watchdog with enough time for app partition switchover, and once the update is completed, run app from new partition and disable watchdog. Update in uboot environment the current appfs partition. 

Any help will be appreciated. Thanks.

**Comment by ejoerns** [comment] 2024-12-06 06:02
> Rauc supports updating rootfs with A/B. I need a redundant way to update app partition. Can we assign a custom script to such updates? A script that can stop the running apps, enable watchdog with enough time for app partition switchover, and once the update is completed, run app from new partition and disable watchdog. Update in uboot environment the current appfs partition.

@bhupiister Is this really just an app partition or the whole rootsf with applications? I wonder how this aligns with enabling it in u-boot and using the HW watchdog.

For the script: Slot updates support hooks that you could use to stop the application:

https://rauc.readthedocs.io/en/latest/using.html#bundle-based-customization-hooks

Depending on how the application depends on the rootfs content, an alternative could be to use the upcoming *artifact updates*. They ensure an atomic update of your application but don't do a full partition switch.

https://rauc.readthedocs.io/en/latest/basic.html#artifact-repositories

**Comment by bhupiister** [comment] 2024-12-06 06:35
My partition scheme would look something like this 

Roofts0

Rootfs1

Appfs 

No hard requirements for redundancy on appfs as i think a logic in the rootfs can be created to flash appfs with updates. At this stage i don't know if i'll need A/B on appfs. 

My application depends on roofts for the libraries it requires to run. Nothing more than that. 

I can give you example of what closely resembles to my application. Assume i am making a video player. The player requires ffmpeg, gstreamer libraries,which will be part of rootfs and requires version updates when needed. The video player which will play the video will be part of the appfs. This will require frequent updates as ill keep on adding features to the player. User may also need space to download mp4 files to play. 

Ill read more on artifact updates and how it can help my use case. 

I am still at planning stage and brainstorming on the best solution.

**Comment by bhupiister** [comment] 2024-12-07 07:20
Hi @ejoerns 

Based on my example in the previous reply here is the graphical representation of the video player app. Would appreciate your suggestion.
The end goal is to have an end-to-end traceability and reproducible system to tackle bugs.

**Option 1**
![Flow for OS build (1)](https://github.com/user-attachments/assets/17f73f4d-e96a-4805-9a37-9b05a0985cbb)

**Option 2**
![Flow for OS build](https://github.com/user-attachments/assets/90d257ad-3e55-4792-a465-bc3f95b7b1de)
